### ISSUE TITLE
Um Jammer Lammy (Europe)

### ISSUE THREAD

**Issue by HanaO00** [alex-free/tonyhax#59] opened 2024-05-31 16:51 UTC
**Game name**: Um Jammer Lammy (Europe)
**Game code**: SCES-01753
**Executable hash**:  MD5 da64abe3270f8ab7ce96d5b3065b0c47
**Triggered at**: APv2 - After the Sony Logo

Hello,

The game [Um Jammer Lammy (Europe)](http://redump.org/disc/5510/) seems to have anti-modchip protection, APv2 by cross-referencing information from your guide and videos, or other sources

On your table, https://alex-free.github.io/tonyhax-international/anti-piracy-bypass It says "no protection"

https://youtu.be/qOJIF1_ufMQ?t=139
https://youtu.be/2tZbjT4Xf9g?t=104
https://darius-saturn.com/forum/viewtopic.php?p=392031&sid=a027551a73d23ad3f44f6cfe8463bd24#p392031
![Capture d’écran_2024-05-31_18-46-13](https://github.com/alex-free/tonyhax/assets/17810985/11ac8454-67eb-4f59-b49d-307c0c9c3556)
Translation

> It allows you to play the game Um Jammer Lammy without having the blocking message, a metal version of Parappa The Rapper which detects spam of ASCII characters SCEA, SCEI and SCEE from chips that are too simple to code that is too old. This does not change anything about the LibCrypt process which is another method of protection. After having fun with an LED, I made a cleaner assembly.

**Comment by alex-free** [comment] 2024-06-02 14:29
> **Game name**: Um Jammer Lammy (Europe) **Game code**: SCES-01753 **Executable hash**: MD5 da64abe3270f8ab7ce96d5b3065b0c47 **Triggered at**: APv2 - After the Sony Logo
> 
> Hello,
> 
> The game [Um Jammer Lammy (Europe)](http://redump.org/disc/5510/) seems to have anti-modchip protection, APv2 by cross-referencing information from your guide and videos, or other sources
> 
> On your table, https://alex-free.github.io/tonyhax-international/anti-piracy-bypass It says "no protection"
> 
> https://youtu.be/qOJIF1_ufMQ?t=139 https://youtu.be/2tZbjT4Xf9g?t=104 https://darius-saturn.com/forum/viewtopic.php?p=392031&sid=a027551a73d23ad3f44f6cfe8463bd24#p392031 ![Capture d’écran_2024-05-31_18-46-13](https://private-user-images.githubusercontent.com/17810985/335658506-11ac8454-67eb-4f59-b49d-307c0c9c3556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzgyNDEsIm5iZiI6MTcxNzMzNzk0MSwicGF0aCI6Ii8xNzgxMDk4NS8zMzU2NTg1MDYtMTFhYzg0NTQtNjdlYi00ZjU5LWI0OWQtMzA3YzBjOWMzNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDE0MTkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNGU3NmI4NjU1Y2U4NzM0MTkyZTYyYmI2YWNkZmI4MjdkYzI0OWE0OGY5ZGFiNDQ2OTZlMDlkYmY2NmY0ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EYEhafkuNTQGJgrLKbh9FsaXjNeg1EO7Um1JdQKhiTM) Translation
> 
> > It allows you to play the game Um Jammer Lammy without having the blocking message, a metal version of Parappa The Rapper which detects spam of ASCII characters SCEA, SCEI and SCEE from chips that are too simple to code that is too old. This does not change anything about the LibCrypt process which is another method of protection. After having fun with an LED, I made a cleaner assembly.

Confirmed this has at least APv1 protection, I missed this game when updating the docs. I'll push out a fix for this today.

**Comment by alex-free** [comment] 2024-06-03 04:40
Also found APv1 in USA Demo release of Um Jammer Lammy. Confirmed that the actual USA release has no protection.

EDC protection is not present from what I can see, looks like another redump inaccuracy in detecting the protection schemes.

v1.5.1 update now supports these games.

**Closed by alex-free** 2024-06-03 04:40 UTC
