### ISSUE TITLE
Earth Warm Jim 2 PAL Xplorer Codes

### ISSUE THREAD

**Issue by JMaxxL** [alex-free/tonyhax#37] opened 2023-07-31 07:04 UTC
Infinite Lives	86624520 5955
                        8662451E 5955
Infinite Energy	865F1D18 59B6
Infinite Shots	866041A4 5C42

couldnt get these to generated TH file

**Comment by alex-free** [comment] 2023-08-01 05:33
86 is not a supported prefix: https://alex-free.github.io/tonyhax-international/gameshark-code-support.html#supported-codes--limits

86 _appears_ to be a PSX Xplorer code type and not a gameshark code type as per: https://gamehacking.org/faqs/hackv500c.html#whatis_gsbutton . Do these codes work with a real GameShark (and not an Xplorer)?

From what I understand, these codes can be converted from Xplorer to GameShark. Maybe THIGSGEN can be updated to support this if true. I'll look into this for you.

**Comment by JMaxxL** [comment] 2023-08-23 03:36
Hello I've been testing the following bug/issue with read error of the "TONYHAXINTGS" file off memory card. I tested this alot before I decided to report it. 

Both of my console's are getting error message over & over again. When I get to the point were it is time to "Press 0" to activate gameshark codes it errors out on perfectly functioning cards. This happens about ATLEAST 20% of the time time on my SCPH-7501 with flashed cheat cart & 30% of the time on FreePSXBoot in last few days so im compelled to report it finally. 

I tested all my cards cleaned them with an eraser & IPA they read perfect in the sony bios, unirom & THi [X] bios I really don't think its the cards or hardware issue with my consoles.

I know I cant be sure & the hardware is 20 years old but my SCPH7501 was in storage for at least 10 years of that time unused. 

I was working on shorting half my videos
Is it possible instead in the code forcing me to RESTART if the TONYHAXINTGS is not read correctly if there is a read error I could just re-seat and press [O] a 2nd or multiple times with tonyhax international booted. Since I know from experience powering off & back on sometimes fixes the read error leaving the memory card right where it is. I just feel something weird might be going on.

**Comment by alex-free** [comment] 2023-08-23 03:38
> All my cards are so old I cant help that fact BUT.........
> 
> 
> 
> Hello I've been testing the following bug/issue with read error of the "TONYHAXINTGS" file off memory card. I tested this alot before I decided to report it. 
> 
> 
> 
> Both of my console's are getting error message over & over again. When I get to the point were it is time to "Press 0" to activate gameshark codes it errors out on perfectly functioning cards. This happens about ATLEAST 20% of the time time on my SCPH-7501 with flashed cheat cart & 30% of the time on FreePSXBoot in last few days so im compelled to report it finally. 
> 
> 
> 
> I tested all my cards cleaned them with an eraser & IPA they read perfect in the sony bios, unirom & THi [X] bios I really don't think its the cards or hardware issue with my consoles.
> 
> 
> 
> I know I cant be sure & the hardware is 20 years old but my SCPH7501 was in storage for at least 10 years of that time unused. 
> 
> 
> 
> I was working on shorting half my videos
> 
> Is it possible instead in the code forcing me to RESTART if the TONYHAXINTGS is not read correctly if there is a read error I could just re-seat and press [O] a 2nd or multiple times with tonyhax international booted. Since I know from experience powering off & back on sometimes fixes the read error leaving the memory card right where it is. I just feel something weird might be going on.

Is this a 1.3.7 specific thing for you?

**Comment by alex-free** [comment] 2023-08-24 19:33
I changed some memory card handling around, so it will display an error code if the MC file can't be read. I can eventually have it able to 'retry by pressing O again' but that might not make it in the next release. The memory card handling is also done a bit more 'correctly' by specifying pad_enable 1 instead of pad_enable 0. I'm hoping this will fix your issue, I really have only encountered what your saying once or twice myself and I think the next update should make it always reliable.

Did you ever see if the Xplorer codes worked on a real gameshark?

**Comment by JMaxxL** [comment] 2023-08-24 20:37
I have suspect because I noticed the slim model was doing it more then the phat model, that right there makes no since. But could it be the controller somehow causing this I did read the controller is actually part of the memory card. same as the PS2 you actually CANT have certain things plugged into the controller port & read memory cards at the same time.

**Comment by JMaxxL** [comment] 2023-08-26 06:27
The end of this video shows the issue happening organically 

https://youtu.be/X95JVmMerV0

**Comment by JMaxxL** [comment] 2023-08-26 08:06
I hope you like the video It took hours and hours to generate all those
files. video is long but actually took even longer setting everything up.
All those folders are months of figuring out what I'd actually use.

**Comment by alex-free** [comment] 2023-08-26 14:26
> here this link is working finally it took months to generate all of these TONYHAXINTGS files hope you like the video the read failure is at the vary end
> 
> 
> 
> https://youtu.be/X95JVmMerV0?si=OaJJM98G6EE23Osr

Is this specifically happening using that fork of ulaunchelf and that hardware? Does using wlaunchelf and real hardware and native usb 1.1 drive make any difference in this case?

**Comment by JMaxxL** [comment] 2023-08-27 06:10
The stable version of wLaunchelf dose not even work to move PS1 files, ulaunchelf dose Ill check back with you over time its hard to force the read error, it just kinda happens.

But did you see the video, you see what I mean eventually over months I got enough custom TONYHAXINTGS library organized  on the PS2 I really don't want it on my PC. Unless I get a new game I wont be on the PC make new files.

**Comment by alex-free** [comment] 2023-08-27 06:25
> The stable version of wLaunchelf dose not even work to move PS1 files, ulaunchelf dose Ill check back with you over time its hard to force the read error, it just kinda happens.
> 
> 
> 
> But did you see the video, you see what I mean eventually over time I got enough custom TONYHAXINTGS library organized  on the PS2 I really don't want it on my PC. Unless I get a new game I wont be on the PC make new files. 

I had the exact opposite result, ulaunchelf broke ps1 compatibility at some point but wlaunchelf always worked with PS1 memory cards copying from USB. I exclusively use the wlaunchelf stable release (I believe the latest from 5 years ago?) with a USB flash drive that works with the PS2 (not all do, IIRC the ones that don't just don't allow you to open the MASS device) and a real Sony PS1 memory card, never had any issues. Any chance you can show me what happens if you try to use wlaunchelf? I'm really curious.

I am quite impressed with how much you use this feature, and I did see the video. You've got me into using it myself even, always appreciate the videos.

I know the issue is intermediate, I am going to do a test for the new version in development, something like turn the console on, read the memory card, turn it off and repeat 100 times on my PSone to compare it to the current v1.3.7.

![image](https://github.com/alex-free/tonyhax/assets/72545918/8f5e27ce-0f08-4c48-82a1-84e925bda898)

![image](https://github.com/alex-free/tonyhax/assets/72545918/b93b093d-7faa-4743-aa42-91e18a32a96a)

![image](https://github.com/alex-free/tonyhax/assets/72545918/cdd619a4-ab12-4a55-9501-f49d1b57ac8f)

**Comment by JMaxxL** [comment] 2023-08-27 06:29
im getting paste failure

**Comment by alex-free** [comment] 2023-08-27 06:30
> im getting paste failure

Do you use mcpaste or the paste option? I think mcpaste caused that but paste works

**Comment by JMaxxL** [comment] 2023-08-27 06:31
no I was told not to use that feature its outdated

**Comment by JMaxxL** [comment] 2023-08-27 06:32
over 100 people watched that video first day

**Comment by alex-free** [comment] 2023-08-27 06:33
> no I was told not to use that feature its outdated 

So you only used mcpaste before? Try paste instead that's what I use. I'm not sure how it could be considered outdated? I'm not even sure what the difference is to be honest but I'm pretty sure mcpaste has either never worked for me for PS1 memory cards or is for PS2 memory cards only maybe?

**Comment by JMaxxL** [comment] 2023-08-27 06:35
Ill use it I was told by PS2homebrew im pretty sure it was them not to use it but im not 100% it was them it was a dev I know that

**Comment by alex-free** [comment] 2023-08-27 06:38
> Ill use it I was told by PS2homebrew im pretty sure it was them not to use it but im not 100% it was them it was a dev I know that

I'm just really curious if that makes wlaunchelf work for you (using paste not mcpaste like in my screenshots) since I've been doing it like that for years. I honestly am not sure about much PS2 stuff I haven't really kept up to date in that scene in a long time so maybe they are right. Maybe wlaunchelf just has some kind of bug in regards to the mcpaste option? If you have a link to that devs comment let me know

**Comment by JMaxxL** [comment] 2023-08-27 06:39
MCPaste might only be for PC1 stuff if you ever read the notes you can tell how mixed up everything is

**Comment by alex-free** [comment] 2023-08-27 17:03
@JMaxxL try this v1.3.8 beta version and let me know if you can get it to error out on reading the memory card because I can't so far
[tonyhax-international-v1.3.8b1.zip](https://github.com/alex-free/tonyhax/files/12448458/tonyhax-international-v1.3.8b1.zip)

**Comment by alex-free** [comment] 2023-09-02 16:42
Memory card issue is fixed in v1.3.8

**Comment by JMaxxL** [comment] 2023-09-04 02:54
It worked really smoothly I wish I knew it was going to fail on me in my video I could have looked more together lol

**Comment by alex-free** [comment] 2023-09-07 17:03
Back to the original issue, these are encrypted Xplorer codes (denoted by the 6 in the 86 prefix). These codes are from https://www.willemssoft.be/index.php?main=22&sub=24 originally. These codes are the 8 type.

There is a converter at https://gamehacking.org/system/psx . So you can convert these from encrypted Xplorer codes to regular gameshark codes which work with Tonyhax International and original GameSharks. I'll comment again after I test these work as GameShark codes

===============
Encrypted Xplorer:

Infinite Lives 
86624520 5955
8662451E 5955

Infinite Energy 
865F1D18 59B6

Infinite Shots 
866041A4 5C42

==========
GameShark:

Infinite Lives 
800CF2C8 0005
800CF2CA 0005

Infinite Energy 
800BCAC0 0064

Infinite Shots 
800AEE4C 03E8

=============

I'm still not exactly sure how the 'encryption' works for the conversions but we have the online converter for now.

**Comment by alex-free** [comment] 2023-09-07 20:24
Tested and all the above codes work :) Closing this for now since I still don't know how to support encrypted codes and can't find info on how they work

**Closed by alex-free** 2023-09-07 20:24 UTC
Labels: enhancement

**Comment by alex-free** [comment] 2023-09-08 01:35
I tested the codes on the NTSC hack version floating around.
