### ISSUE TITLE
Memcardpro no longer is detected when Tonyhax Int 1.56/1.57 runs from a cheat cartridge

### ISSUE THREAD

**Issue by kimbapslice** [alex-free/tonyhax#69] opened 2024-10-09 15:55 UTC
On my ps1 scph-7501 running stock cd drive, Gameshark cheat cartridge flashed with 1.57:

Memcardpro no longer is detected when Tonyhax Int 1.56/1.57 runs from a cheat cartridge, thus gameid isn't properly passed onto the memcardpro.

It seems with version 1.56/1.57 the memcardpro(and similar devices) detection timing change might be the culprit as 1.55 works correctly from the cartridge.

Note: the functionality of having freepsxboot version of tonyhax int installed on the memcardpro does work and gameid changes the "card" to the correct game in 1.55/1.56/1.57 (without the cartridge). Therefore the detection timing change introduced in 1.56 seems to only break the cartridge version. Cartridge boots too fast and doesn't see the mcpro.

**Comment by alex-free** [comment] 2024-10-10 02:05
> On my ps1 scph-7501 running stock cd drive, Gameshark cheat cartridge flashed with 1.57:
> 
> Memcardpro no longer is detected when Tonyhax Int 1.56/1.57 runs from a cheat cartridge, thus gameid isn't properly passed onto the memcardpro.
> 
> It seems with version 1.56/1.57 the memcardpro(and similar devices) detection timing change might be the culprit as 1.55 works correctly from the cartridge.
> 
> Note: the functionality of having freepsxboot version of tonyhax int installed on the memcardpro does work and gameid changes the "card" to the correct game in 1.55/1.56/1.57 (without the cartridge). Therefore the detection timing change introduced in 1.56 seems to only break the cartridge version. Cartridge boots too fast and doesn't see the mcpro.

Thanks for the report. The memcard pro check was moved closer toward startup in order to detect if the 'remove freepsxboot memory card now' text should be sent or not (no need to remove the freepsxboot memory card if it's a mcpro).

I added an additional waiting period before pinging the device. This seems necessary now (and is more correct anyways). I hope this fixes it. Really, thanks for reaching out. GameID support wasn't very straight forward to ask and there are like no open source examples (Unirom, xstation, etc. are closed source) so I've just been learning as I go.

 Let me know how it goes with this beta
[tonyhax-international-v1.5.8b1.zip](https://github.com/user-attachments/files/17320759/tonyhax-international-v1.5.8b1.zip)

**Comment by kimbapslice** [comment] 2024-10-10 02:27
Unfortunately, 1.5.8b1 still does not correctly detect the memcardpro (first slot).

Tonyhax Int is my favorite ps1 softmod! Thanks for all of your work on it!

**Comment by kimbapslice** [comment] 2024-10-10 02:36
![PXL_20241010_023518168](https://github.com/user-attachments/assets/dc4a31fa-e0c6-4ea5-bbaf-439fc2741834)
![PXL_20241010_023551555](https://github.com/user-attachments/assets/b7dac8f7-0e44-473f-b3ec-1d329866455b)

**Comment by alex-free** [comment] 2024-10-10 02:38
> Unfortunately, 1.5.8b1 on a cartridge still does not correctly detect the memcardpro (first slot).
> 
> Tonyhax Int is my favorite ps1 softmod! Thanks for all of your work on it!

I've tripled the waiting period on startup, I hope this is enough. The good news is we know what the problem is and I can fix it. Thinking this might be enough:
[tonyhax-international-v1.5.8b2.zip](https://github.com/user-attachments/files/17321030/tonyhax-international-v1.5.8b2.zip)

**Comment by kimbapslice** [comment] 2024-10-10 02:48
Sorry :( 1.5.8b2 cart is still not detecting the memcardpro

**Comment by alex-free** [comment] 2024-10-10 02:56
> Sorry :( 1.5.8b2 cart is still not detecting the memcardpro

I think we got it this time. The wait was not being trippled correctly until this beta 3:
[tonyhax-international-v1.5.8b3.zip](https://github.com/user-attachments/files/17321153/tonyhax-international-v1.5.8b3.zip)

If this doesn't work, we can increase the wait time correctly now. But this should give it enough time to 'catch up' with the mcpro. The rom loader is too fast @mottzilla 's code is too efficient!

Thank you for your sacrifice of CD-Rs!

**Comment by kimbapslice** [comment] 2024-10-10 03:06
1.5.8b3 does not detect :(

I agree, it's too fast and efficient :)

**Comment by alex-free** [comment] 2024-10-10 03:10
> 1.5.8b3 does not detect :(
> 
> I agree, it's too fast and efficient :)

Alright, 6x the normal waiting period:
[tonyhax-international-v1.5.8b4.zip](https://github.com/user-attachments/files/17321259/tonyhax-international-v1.5.8b4.zip)

**Comment by alex-free** [comment] 2024-10-10 03:18
Maybe it's not the waiting period (or perhaps there needs to be a waiting period + stoppad() call since perhaps, the BIOS is calling statpad() around the time of startup). Curious how beta 4 goes. I think it could be either.

**Comment by kimbapslice** [comment] 2024-10-10 03:31
Beta4 is still no go unfortunately

**Comment by alex-free** [comment] 2024-10-10 03:34
> Beta4 is still no go unfortunately

Thank you really for the testing. I don't have too many CD-Rs left and won't be able to get some more anytime soon. Very much so  appreciate your time.

Lets try this. It may be able to be optimized to be faster but I want the best chance of it working now on your console. It calls stoppad() and then does a 12x wait period. 

[tonyhax-international-v1.5.8b5.zip](https://github.com/user-attachments/files/17321407/tonyhax-international-v1.5.8b5.zip)

**Comment by kimbapslice** [comment] 2024-10-10 03:47
The wait is definitely noticeable after unlocking the drive, but it doesn't detect it at the beginning.

The behavior in 1.5.5 where memcardpro is detected after the cd loads seems to work without issue.

**Comment by alex-free** [comment] 2024-10-10 03:54
> The wait is definitely noticeable after unlocking the drive, but it still doesn't detect it at the beginning. (I have a video but it's too but to be uploaded...)
> 
> The behavior in 1.5.5 where memcardpro is detected after the cd loads seems to work without issue.

It may end up better to go back to the v1.5.5 behavior and just remove the freepsxboot text. But that's the easy way out, and I'm kind of curious why this even happens. I tried some other things here as well in beta 6
[tonyhax-international-v1.5.8b6.zip](https://github.com/user-attachments/files/17321603/tonyhax-international-v1.5.8b6.zip)

**Comment by kimbapslice** [comment] 2024-10-10 04:00
Yay, you did it. It sent the gameid after it detected the disk(id). Memcardpro successfully changed to the correct game.
I guess this way, you can remove the 12x wait period at the beginning.

**Comment by alex-free** [comment] 2024-10-10 04:07
> Yay, you did it. It sent the gameid after it detected the disk(id). Memcardpro successfully changed to the correct game. I guess this way, the 12x wait period at the beginning isn't needed?

Possibly. We need to figure out what is actually the bare minimum needed. Beta 6  is:
1) Waiting 12x
2) startpad()
3)stoppad()
checking fro mc pro

So now, I need to figure out what fixed it  A bit tedious, but we can do it.

This build doesn't send startpad(). Lets start with that.  Let me know if it still works :)
[tonyhax-international-v1.5.8b7.zip](https://github.com/user-attachments/files/17321705/tonyhax-international-v1.5.8b7.zip)

**Comment by kimbapslice** [comment] 2024-10-10 04:14
B7 doesn't send gameid

**Comment by alex-free** [comment] 2024-10-10 04:17
> B7 doesn't send gameid

Cool I was right about the BIOS startpad() conflict. Lets try this. It does:
1) 1x wait
2) startpad()
3) stoppad()
4) check for mcpro

[tonyhax-international-v1.5.8b8.zip](https://github.com/user-attachments/files/17321886/tonyhax-international-v1.5.8b8.zip)

**Comment by kimbapslice** [comment] 2024-10-10 04:23
Yes! Beta8 is the ticket. Says GameID device detected at the beginning and then successfully sends gameid after disk is detected.

**Comment by alex-free** [comment] 2024-10-10 04:24
> Yes! Beta8 is the ticket. Says GameID device detected at the beginning and then successfully sends gameid after disk is detected. Woohoo!

Incredible. No more tests needed! You're a trooper. This will essentially be v1.5.8 final, when that releases we can close this issue.

**Comment by kimbapslice** [comment] 2024-10-10 04:32
Thank you for the quick resolution!

**Comment by alex-free** [comment] 2024-10-10 04:56
> Thank you for the quick resolution!

I hate to do this. but I think there is one more optimization we can do. I don't think we need to wait at all. Can you please try this build? Many thanks:
[tonyhax-international-v1.5.8b9.zip](https://github.com/user-attachments/files/17322175/tonyhax-international-v1.5.8b9.zip)

**Comment by kimbapslice** [comment] 2024-10-10 05:09
Beta9 works great as well. Really fast!

**Comment by alex-free** [comment] 2024-10-10 05:11
> Beta9 works great as well. Really fast!

What an interesting thing this has been! Thank you. This is the best solution and outcome by far.

**Comment by alex-free** [comment] 2024-10-10 18:24
Fixed in v1.5.8 :)

**Closed by alex-free** 2024-10-10 18:24 UTC
Labels: bug
