### ISSUE TITLE
Open error 19

### ISSUE THREAD

**Issue by MicroshaftLLC** [alex-free/tonyhax#33] opened 2023-06-27 17:21 UTC
I cannot seem to run any game from the Tonyhax loader. No matter what I do, when it tries to read the executable header, I get thrown with Open Error 19.

TonyHax version is at the latest stable version.
I'm using the PS1 Demoswap Patcher on the USA version of Namco Museum 3. My console model is a SCPH-7501, hardware rev C. I do not know the motherboard version, but the BIOS is v4.1, and the integrity check has passed.

**Comment by alex-free** [comment] 2023-06-28 07:01
PS1 DemoSwap Patcher is using IIRC version 1.0.9 of International which is almost a year old. I am now at International v1.3.5, a lot has changed since then. I am aware I need to get around to updating that...

Is there any way you can run International v1.3.5 on your console? If you only can use DemoSwap try v1.0/v1.0.1 of it (which contains OG Tonyhax v1.4.3 instead of the old version of International v1.0.9). That might get you to the point where you can run International v1.3.5.

**Comment by MicroshaftLLC** [comment] 2023-06-28 08:06
Still same error. I'm using a memorex cool colors cd-r disc at lowest speed on my PC (4x)

**Comment by alex-free** [comment] 2023-06-28 18:43
> Still same error. I'm using a memorex cool colors cd-r disc at lowest speed on my PC (4x)

If you turn your console vertical (to the left or right standing up on either side) and try the whole thing again does it work? I can only think this is a disc read issue with the low quality memorex CD-Rs but I can't remember what error 19 is

**Comment by MicroshaftLLC** [comment] 2023-06-29 02:24
Still nothing. I think I'll just get a flash cart instead. Thanks, anyways.

**Comment by alex-free** [comment] 2023-06-29 03:59
> Still nothing. I think I'll just get a flash cart instead. Thanks, anyways.

That sucks :( I need to update demoswap patcher. Did you ever try booting the Tonyhax International Boot CD from the Tonyhax loader started via demoswap?

I really can't even find info on error 19. I am so curious about what's going on here.

**Comment by alex-free** [comment] 2023-06-30 00:36
@MicroshaftLLC I updated DemoSwap with International v1.3.5, let me know if anything changes? https://alex-free.github.io/ps1demoswap

**Comment by MicroshaftLLC** [comment] 2023-07-05 01:56
OK, so I bought some Verbatim CD-R discs, which is 700MB/80Min at max 52x speed.

This is the ATIP information:

ATIP info from disk:
  Indicated writing power: 5
Disk Is not unrestricted
Disk Is not erasable
  Disk sub type: Medium Type A, high Beta category (A+) (3)
  ATIP start of lead in:  -11634 (97:26/66)
  ATIP start of lead out: 359846 (79:59/71)
Disk type:    Short strategy type (Phthalocyanine or similar)
Manuf. index: 3
Manufacturer: CMC Magnetics Corporation

Could those work?

**Comment by alex-free** [comment] 2023-07-05 01:59
> OK, so I bought some Verbatim CD-R discs, which is 700MB/80Min at max 52x speed.
> 
> 
> 
> This is the ATIP information:
> 
> 
> 
> ATIP info from disk:
> 
>   Indicated writing power: 5
> 
> Disk Is not unrestricted
> 
> Disk Is not erasable
> 
>   Disk sub type: Medium Type A, high Beta category (A+) (3)
> 
>   ATIP start of lead in:  -11634 (97:26/66)
> 
>   ATIP start of lead out: 359846 (79:59/71)
> 
> Disk type:    Short strategy type (Phthalocyanine or similar)
> 
> Manuf. index: 3
> 
> Manufacturer: CMC Magnetics Corporation
> 
> 
> 
> Could those work?

They _could_ work but I highly don't recommend them. Those are the 'fake' Verbatim CD-Rs. They are Verbatim branded but just as terrible as the Maxell Music CD-Rs. What you want is Verbatim DataLifePlus, Verbatim UltraLifePlus, or CMC Pro. I recently tried CMC Pro and I think they have the best results.

Still give it a go though and let me know since you already have them. Again they should work but other CD-Rs work better.

**Comment by MicroshaftLLC** [comment] 2023-07-05 02:47
OK, so I've made the DemoSwap installed onto my dumped game of Namco Museum Vol 3 (USA). Do I use ImgBurn to burn the cue file? And if so, what settings should I use?

**Comment by alex-free** [comment] 2023-07-05 02:49
> OK, so I've made the DemoSwap installed onto my dumped game of Namco Museum Vol 3 (USA). Do I use ImgBurn to burn the cue file? And if so, what settings should I use?

Yes you can use IMGBurn, set the write speed to 1x (this will make it write at the slowest possible speed your drive supports, which will be actually higher then 1x). Let me know what speed it reports that your actually writing at. It will say the actual speed in the log window that pops up when you start imgburn

**Comment by MicroshaftLLC** [comment] 2023-07-05 02:52
OK, so the cd writer is using 8x for the write speed, as that's the lowest drive speed. If you wish, if there is any errors, I can attach the log?

**Comment by MicroshaftLLC** [comment] 2023-07-05 02:53
And do I check Verify when the burning is done?

**Comment by alex-free** [comment] 2023-07-05 02:54
> OK, so the cd writer is using 8x for the write speed, as that's the lowest drive speed. If you wish, if there is any errors, I can attach the log?

That's good enough! 8x speed is great. I think the verify needs to be unchecked for it to work since the image was 'patched' it may cause it to fail the verify but I can't remember. If it does fail the verify it's ok.

**Comment by MicroshaftLLC** [comment] 2023-07-05 03:16
Now I get the letter p when it loads TonyHax International.

**Comment by alex-free** [comment] 2023-07-05 03:17
> Now I get the letter p when it loads TonyHax International.

Can you send a picture?

**Comment by MicroshaftLLC** [comment] 2023-07-05 03:20
Here
![20230704_221833](https://github.com/alex-free/tonyhax/assets/85321103/ef118973-0088-4d28-aa34-8ee7f24936f7)

**Comment by alex-free** [comment] 2023-07-05 03:46
> Here ![20230704_221833](https://user-images.githubusercontent.com/85321103/251027765-ef118973-0088-4d28-aa34-8ee7f24936f7.jpg)

This bug should be fixed in v1.0.7, do you mind giving it another go? Use the new v1.0.7 and patch a clean image of the Namco Museum 3 disc, and start again.

**Comment by MicroshaftLLC** [comment] 2023-07-05 03:59
Still nothing, I'll get some better quality CDs.

**Comment by alex-free** [comment] 2023-07-05 04:00
> 
> 
> Still nothing, I'll get some better quality CDs.

What happens with v1.0.7?

**Comment by alex-free** [comment] 2023-07-05 06:05
@MicroshaftLLC I confirmed the bug is fixed in v1.0.8 with the 'p' thing. Sorry about the back and forth. Let me know with the new version 1.0.8.

**Comment by alex-free** [comment] 2023-07-10 10:58
@MicroshaftLLC  ever get a chance?

**Comment by MicroshaftLLC** [comment] 2023-07-10 12:20
I'll just get a flash cart, this is all a bit too much, but thanks.

**Closed** 2023-07-10 16:03 UTC
Labels: bug
