### ISSUE TITLE
Please remove interaction required for proceeding

### ISSUE THREAD

**Issue by L10N37** [alex-free/tonyhax#29] opened 2023-06-08 08:40 UTC
https://www.youtube.com/watch?v=uGdz4BEfnRk

Can we have a removal of the having to press 'X' to proceed :)
I want to leave this plugged in perma for this system, check out the video

**Comment by alex-free** [comment] 2023-06-08 19:25
> https://www.youtube.com/watch?v=uGdz4BEfnRk
> 
> 
> 
> Can we have a removal of the having to press 'X' to proceed :)
> 
> I want to leave this plugged in perma for this system, check out the video

Lol I did see the video I never expected that use case.

I can not remove the 'press X' for the mainline version because it is how this all works on Japanese consoles that are not modded. The Japanese consoles need to wait for when the user says to spin up the backup disc because they would be actually swapping a real NTSC-J game disc at that point out and replacing it with the backup or import disc, all while the motor is stopped for that step. The press X tells the console to start the motor back 

It's funny because if you had an American or European console it would already just auto-boot into X-station since those work differently, there is no press X after disc swap on those consoles.

I do have a solution to this. A special '-Xstation' version of the ROM that will be a different file entirely from the mainline version. Not only can I remove the press X, I can remove multiple other steps since it's an X-Station and not a stock console and this can get really fast I think. I'm going to whip something up but it'll be on you to test as I don't have an X-Station. I'll send you what I have later tonight if it's ready then.

**Comment by L10N37** [comment] 2023-06-09 00:44
Thanks so much!  I only have to burn a new disc and can re flash the cart :)

**Comment by alex-free** [comment] 2023-06-09 03:24
> Thanks so much! I only have to burn a new disc and can re flash the cart :)

Alright I am thinking this will work. I stripped everything I could think of to increase speed.

in this zip go to xstation folder and use the rom flasher bin/cue or the .rom file in that folder.

Look forward to results
[tonyhax-international-v1.3.4b.zip](https://github.com/alex-free/tonyhax/files/11701896/tonyhax-international-v1.3.4b.zip)

**Comment by L10N37** [comment] 2023-06-10 08:00
Hey dude, going to check it out shortly. I didn't see the notification. Much appreciated and will update shortly.

**Comment by L10N37** [comment] 2023-06-10 09:29
Thanks again, this will be staying in my system. So much quicker after an IGR to get back to the menu. Its down another ~2 seconds. It was about 11seconds with the old version, 21 seconds stock system, 9 seconds now :)

**Comment by L10N37** [comment] 2023-06-10 12:09
What do you think about adding some debugging stuff in for aiding in the development of PICOstation?
i.e. i can get Disc error type D code 12 atm.

**Comment by alex-free** [comment] 2023-06-10 16:43
> What do you think about adding some debugging stuff in for aiding in the development of PICOstation?
> 
> i.e. i can get Disc error type D code 12 atm. 
> 
> 
> 
> I mean if it sounds easy for you, could you read out the contents of the images of the SD card, list them and then select which one to attempt to boot? (ugh jumped the gun here actually, picostation is specifically mounting UNIROM.CUE/ BIN atm)

So no issues? That error is a disc read issue.

**Comment by alex-free** [comment] 2023-06-10 16:43
> Thanks again, this will be staying in my system. So much quicker after an IGR to get back to the menu. Its down another ~2 seconds. It was about 11seconds with the old version, 21 seconds stock system, 9 seconds now :)
> 
> 
> 
> 

So everything works as expected?

**Comment by alex-free** [comment] 2023-06-11 14:13
@L10N37

**Comment by L10N37** [comment] 2023-06-11 14:14
Hey dude, zero issues, boots xstation fine. 2 seconds faster :)

**Comment by alex-free** [comment] 2023-06-11 14:16
> Hey dude, zero issues, boots xstation fine. 2 seconds faster :)  , thanks again!

Excellent! Will be in v1.3.4 release, I'll write some documentation on the feature as well.

**Comment by L10N37** [comment] 2023-06-11 14:55
That's awesome! do you think there could be more specific errors thrown for PICOboot development? adding debugging in adds overhead and it's flakey enough as it is.

**Comment by L10N37** [comment] 2023-06-11 14:57
something along the lines of what it expected to receive verse what it did receive would be awesome

**Comment by alex-free** [comment] 2023-06-11 15:11
> something along the lines of what it expected to receive verse what it did receive would be awesome

I think you would be better served creating a CDROM Debugger program that has a bunch of test cases and verbose output. That would be immensely better then anything tonyhax could do for you. I'd write a menu that does specific things like read files seek initialize play fmv load sprite etc.

If you don't have one already I'd get a serial cable or use socram8888's joy mon. You could set up literal prinf debugging (and alot of games still will actually print stuff over serial if activated correctly)

**Comment by L10N37** [comment] 2023-06-11 15:20
OK this sounds better :)

**Comment by L10N37** [comment] 2023-06-11 15:40
So, one weird thing i didnt mention. When you load a game now, xstation kicks you back to tonyhax international and tonyhax international launches the game.

**Comment by L10N37** [comment] 2023-06-11 15:48
Also confirmed short and long resets maintain functionality as well

**Comment by alex-free** [comment] 2023-06-11 15:49
> So, one weird thing i didnt mention. When you load a game now, xstation kicks you back to tonyhax international and tonyhax international launches the game.

I looked and it appears there is a full boot and a fast boot option in xStation. I would think fast boot would not cause that behavior but full boot should cause that behavior . Can you confirm?

**Comment by alex-free** [comment] 2023-06-11 16:21
I also realized that I removed the option to boot into the Sony BIOS from International if the CD Drive is open for the Xstation build. I restored that ability as well as the GameShark functions in this build, let me know if this works as expected.

[tonyhax-international-v1.3.4.zip](https://github.com/alex-free/tonyhax/files/11715150/tonyhax-international-v1.3.4.zip)

**Comment by L10N37** [comment] 2023-06-11 16:27
I must have accidentally full booted. I was positive i just hit X twice, I've never accidently full booted.. ever. But yeah, its launching straight from Xstation. It's a fair wack of unplug this, plug that in, edit my BIN file with your new release, burn it, set up my other ps1 that i use just for making carts etc. from CD. I will definitely confirm the lid open goes into BIOS ASAP. It's downloaded. I am just in the middle of something :P

**Comment by alex-free** [comment] 2023-06-11 16:30
> I must have accidentally full booted. I was positive i just hit X twice, I've never accidently full booted.. ever. But yeah, its launching straight from Xstation. It's a fair wack of unplug this, plug that in, edit my BIN file with your new release, burn it, set up my other ps1 that i use just for making carts etc. from CD. I will definitely confirm the lid open goes into BIOS ASAP. It's downloaded. I am just in the middle of something :P

Cool. International will replace the Sony bios screens so that's why the full boot would cause international to start up again. That is also why I restored the ability to press X with the cd drive open to boot the Sony bios so you can access the memory card manager and CD player without physically removing the cart. Keep in mind the Sony bios booted via international can't load any games (not implemented yet if ever).

**Comment by L10N37** [comment] 2023-06-11 16:31
that's really not an issue at all

**Comment by alex-free** [comment] 2023-06-11 16:54
> that's really not an issue at all

If your talking about the Sony BIOS booted via International not able to boot games, I agree hence why it still isn't implemented.

**Comment by alex-free** [comment] 2023-06-11 23:09
@L10N37 let me know when you can confirm the new build works as expected. I'll be releasing v1.3.4 with this and much improved documentation all around. I'm getting ready to push that new release right now.

**Comment by L10N37** [comment] 2023-06-12 03:44
Ok, i will burn it in the next hour or so , won't be long

**Comment by L10N37** [comment] 2023-06-12 04:28
2 coasters on this one haha, Unfortunately it hangs on 'stopping motor' if you leave the drive lid open.

**Comment by alex-free** [comment] 2023-06-12 06:01
> 2 coasters on this one haha, Unfortunately it hangs on 'stopping motor' if you leave the drive lid open.

Sorry. Lets try this
[tonyhax-international-v1.3.4b2.zip](https://github.com/alex-free/tonyhax/files/11718556/tonyhax-international-v1.3.4b2.zip)

**Comment by alex-free** [comment] 2023-06-12 06:02
I can rename the rom file if it helps. But I know why your doing all of that :)

**Comment by L10N37** [comment] 2023-06-12 06:03
It's all good, I just rename it to thax.rom and stick in thax folder. .. yeah because my carts use AM29F01 memory (I think thats it) and NXFlash doesn't and isn't ever going to support it.

**Comment by alex-free** [comment] 2023-06-12 06:08
> It's all good, I just rename it to thax.rom and stick in thax folder. The bootdisc for unirom is used for padding (or i could boot this with modchip and flash with it) .. yeah because my carts use AM29F01 memory (I think thats it) and NXFlash doesn't and isn't ever going to support it.

I definitely understand why your doing what  you are for the cart :)

The last build should work as intended. If you leave the drive lid open on power on it should allow you to press X to boot the Sony BIOS. Otherwise if it is closed it should auto-boot like before.

**Comment by L10N37** [comment] 2023-06-12 06:09
burning now

**Comment by L10N37** [comment] 2023-06-12 06:17
Yeah this works, drive lid open at boot or reset, press X

...loading sony bios (this is faster too)

Then CD Player and Memory card selection :) cool
Need to change my JP BIOS to US eventually :P

**Comment by alex-free** [comment] 2023-06-12 06:22
> Yeah this works, drive lid open at boot or reset, press X
> 
> 
> 
> ...loading sony bios (this is faster too)
> 
> 
> 
> Then CD Player and Memory card selection :) cool
> 
> Need to change my JP BIOS to US eventually :P

FUCK YES DUDE YES

I forgot some defines before (I know your a programmer to). So basically to explain, the #if defined XSTATION code path is a mix of the #if defined ROM and the expectation of essentially a modchip. That's why we can auto-boot Japanese consoles with xStation. If everything is as good as you say then v1.3.4 should be released later today :)

**Comment by alex-free** [comment] 2023-06-12 06:24
Also, why would you ever replace the BIOS? Espicallu woth an Xstation I see zero point

**Comment by L10N37** [comment] 2023-06-12 06:25
memory card management, it's not ingrained in memory or anything

**Comment by alex-free** [comment] 2023-06-12 06:28
> memory card management, it's not ingrained in memory or anything

Please elaborate

**Comment by L10N37** [comment] 2023-06-12 06:55
...It's in japanese

**Comment by alex-free** [comment] 2023-06-12 07:00
> ...It's in japanese

Fair enough

**Comment by alex-free** [comment] 2023-06-14 01:47
Can you verify this build still works as expected for you? The previous build screwed up the non-Xstation versiosn I restarted from scratch with this one.
[tonyhax-international-v1.3.4b3.zip](https://github.com/alex-free/tonyhax/files/11740750/tonyhax-international-v1.3.4b3.zip)

**Comment by alex-free** [comment] 2023-06-14 20:12
[tonyhax-international-v1.3.4b4.zip](https://github.com/alex-free/tonyhax/files/11750156/tonyhax-international-v1.3.4b4.zip)
Newer build above

**Comment by alex-free** [comment] 2023-06-15 00:08
Please disregard previous builds. This feature is now in v1.3.4. If you have issues let me know as it does differ from what you said was working.

**Closed by alex-free** 2023-06-15 00:08 UTC
Labels: enhancement

**Comment by L10N37** [comment] 2023-06-15 07:21
You changed this again? I doubt there's any point changing my flash cart. It's going to be permanently in the console. As much as i always loved the ps1 start up sounds its so much better getting straight into a game, especially with the xstation and IGR when you want to quickly switch games.

**Comment by alex-free** [comment] 2023-06-15 11:13
> You changed this again? I doubt there's any point changing my flash cart. It's going to be permanently in the console. As much as i always loved the ps1 start up sounds its so much better getting straight into a game, especially with the xstation and IGR when you want to quickly switch games. 

Would appreciate it just to make sure it works exactly as per the new docs https://github.com/alex-free/tonyhax/blob/master/xstation.md

**Comment by alex-free** [comment] 2023-06-15 13:01
> I will test it, but i didn't have to open or close the lid on full boot...? I guess this was implemented for cheat stuff (which a mate actually asked me about!)
> 
> 
> 
> Let me test it tomorrow :)

Yea that was a bug. It should require that to allow GameShark codes when doing a full boot.

The startup from power on doesn't require opening/closing the lid tho like before.

And fastboot will just jump into the game like before too.
Thanks
